# Generated by Django 2.1.1 on 2018-09-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageBook',
            fields=[
                ('book_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=50)),
            ],
        ),
    ]
