# Generated by Django 2.1.1 on 2018-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloPython2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
