# Generated by Django 2.1.1 on 2018-09-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloPython2', '0002_teacher_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='addres',
            field=models.CharField(default='changsha', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(default='wo like python', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(default='0', max_length=1),
        ),
    ]
