# Generated by Django 2.1.1 on 2018-09-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloPython2', '0003_auto_20180914_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(default='wo like python', max_length=200, null=True),
        ),
    ]
