# Generated by Django 2.1.1 on 2018-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloPython2', '0004_auto_20180914_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='addres',
            field=models.CharField(default='changsha', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
    ]
